# Generated by Django 3.1.7 on 2021-03-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_auto_20210302_1540"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="card",
            new_name="type",
        ),
    ]
